"""add indexes for foreign keys and event search filters

Revision ID: 08f03e6a3bd1
Revises: c46d52daba3b
Create Date: 2026-08-19 16:23:17.389667

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "08f03e6a3bd1"
down_revision: str | None = "c46d52daba3b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_event_category"), "event", ["category"], unique=False)
    op.create_index(op.f("ix_event_date"), "event", ["date"], unique=False)
    op.create_index(op.f("ix_event_organizer_id"), "event", ["organizer_id"], unique=False)
    op.create_index(op.f("ix_event_status"), "event", ["status"], unique=False)
    op.create_index(op.f("ix_reservation_customer_id"), "reservation", ["customer_id"], unique=False)
    op.create_index(op.f("ix_reservation_event_id"), "reservation", ["event_id"], unique=False)
    op.create_index(op.f("ix_reservationseat_reservation_id"), "reservationseat", ["reservation_id"], unique=False)
    op.create_index(op.f("ix_seat_event_id"), "seat", ["event_id"], unique=False)
    op.create_index(op.f("ix_ticket_customer_id"), "ticket", ["customer_id"], unique=False)
    op.create_index(op.f("ix_ticket_event_id"), "ticket", ["event_id"], unique=False)
    op.create_index(op.f("ix_ticket_reservation_id"), "ticket", ["reservation_id"], unique=False)
    op.create_index(op.f("ix_ticket_seat_id"), "ticket", ["seat_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ticket_seat_id"), table_name="ticket")
    op.drop_index(op.f("ix_ticket_reservation_id"), table_name="ticket")
    op.drop_index(op.f("ix_ticket_event_id"), table_name="ticket")
    op.drop_index(op.f("ix_ticket_customer_id"), table_name="ticket")
    op.drop_index(op.f("ix_seat_event_id"), table_name="seat")
    op.drop_index(op.f("ix_reservationseat_reservation_id"), table_name="reservationseat")
    op.drop_index(op.f("ix_reservation_event_id"), table_name="reservation")
    op.drop_index(op.f("ix_reservation_customer_id"), table_name="reservation")
    op.drop_index(op.f("ix_event_status"), table_name="event")
    op.drop_index(op.f("ix_event_organizer_id"), table_name="event")
    op.drop_index(op.f("ix_event_date"), table_name="event")
    op.drop_index(op.f("ix_event_category"), table_name="event")
    # ### end Alembic commands ###
